### ISSUE TITLE
404 Not Found "Wrong path

### ISSUE THREAD

**Issue by Mais316** [artemkin/git-lfs-server#2]
I am not able to push to bare repository

Create a bare repo
Cloned it to local repo
installed git-lfs on client
then
git lfs track *.rpm
git add "file.rpm"
git commit -m "test"
git lfs ls-files --> shows the file

editing .gitconfig to point to server url
from local repo
git push origin master
then entering credentials and keep uploading

at server
./lfs_server.sh -s ip address
2016-02-12 19:18:47.508593Z Listening for HTTP on ip_address:8080
2016-02-12 19:20:43.007939Z Error ip_address "POST /objects/batch HTTP/1.1" 404 Not Found "Wrong path

I am using my home dir and its shared between client and server so .gitconfig is the same

could you please clarify as i understand all whats need from server side is

[user@git lfs_server]# ls -rlt
total 4
drwxrwxrwx. 2 owner owner 47 Aug 26 13:14 lib
-rwxrwxrwx. 1 owner owner 199 Aug 26 13:14 lfs_server.sh
drwxrwxrwx. 2 owner owner 23 Aug 26 13:14 bin
[user@git]# cd
[user@git]# ./lfs_server.sh -s ip_address

please help

**Comment by Mais316** [comment]
Also is this configuration suitable for Enterprise implementation to host large binary files

**Comment by artemkin** [comment]
Hmm... I've tested it (on Mac OS X) using Git LFS client 1.1.1 and everything works just fine.

The message "POST /objects/batch HTTP/1.1" 404 Not Found "Wrong path" means it tried to use the fresh new [batch API](https://github.com/github/git-lfs/blob/master/docs/api/http-v1-batch.md), and then fell back to original API, as batch API is not supported yet. But, it is valid situation. In my case files all files are uploaded correctly.

Which error did you get on `git push`?

**Comment by Mais316** [comment]
last thing that error disappear but files are stuck in upload status neither got uploaded or there is any error 
client is redhat6 and server is redhat 7.2

**Comment by artemkin** [comment]
@Mais316 is this still actual?

**Comment by Mais316** [comment]
no its working fine now thanks

**Comment by LionZXY** [comment]
Actual :(
`2017-09-22 11:53:41.732594+02:00 Listening for HTTP on 127.0.0.1:8082
2017-09-22 11:54:03.801901+02:00 Error 127.0.0.1 "POST /locks/verify HTTP/1.0" 404 Not Found "Wrong path"
2017-09-22 11:54:07.291414+02:00 Error 127.0.0.1 "POST /objects/batch HTTP/1.0" 404 Not Found "Wrong path"
2017-09-22 11:58:14.093541+02:00 Error 127.0.0.1 "POST /locks/verify HTTP/1.0" 404 Not Found "Wrong path"
2017-09-22 11:58:17.013208+02:00 Error 127.0.0.1 "POST /objects/batch HTTP/1.0" 404 Not Found "Wrong path"

`

**Comment by artemkin** [comment]
@LionZXY I guess it tries to use Batch API (not implemented), and then fall back to original API. Even if you see such "errors" in a log, it is expected to work correctly, isn't it?

**Comment by jespertheend** [comment]
Doesn't seem to be working for me.
I do `git push` on the client and I get
```
Git LFS: (0 of 1 files) 0 B / 1.23 KB                                                                                                                                                                                                                                                                                        
batch response: Wrong path
error: failed to push some refs to 'wf2@wf2:wf2.git'
```

The server says
```
2017-09-25 16:14:46.038519+02:00 Listening for HTTP on jespertheend.com:8080
2017-09-25 16:15:20.760048+02:00 Error 145.120.30.102 "POST /objects/batch HTTP/1.1" 404 Not Found "Wrong path"
```
and the `.lfs/objects` folder is empty

**Comment by LionZXY** [comment]
In my case reason for crash - nginx proxy_pass settings.

**Comment by jespertheend** [comment]
I'm not using nginx :/

**Comment by artemkin** [comment]
Yeah, it seems new git LFS clients don't fallback to Basic Transfer API, even if ask them explicitly. Need to figure out how to fix that.

**Comment by cmorent** [comment]
I am experiencing the exact same issue that @jespertheend!

**Comment by tomitrescak** [comment]
I'm getting "No connection could be made because the target machine actively refused it ;("

This is my .gitlfs

```
[lfs]
url = "http://<myserver>:8080
```

**Comment by tomitrescak** [comment]
Hi, same issue here.

```
tomas@hugo:~/lfs_server$ ./lfs_server.sh -verbose -p 3999
2017-11-04 08:46:11.000477+11:00 Listening for HTTP on 127.0.0.1:3999
2017-11-04 08:46:33.792207+11:00 Error 127.0.0.1 "GET / HTTP/1.1" 404 Not Found "Wrong path"
2017-11-04 08:47:17.228939+11:00 Error 127.0.0.1 "POST /locks/verify HTTP/1.1" 404 Not Found "Wrong path"
2017-11-04 08:47:19.144525+11:00 Error 127.0.0.1 "POST /objects/batch HTTP/1.1" 404 Not Found "Wrong path"
2017-11-04 08:47:19.287510+11:00 Error 127.0.0.1 "POST /objects/batch HTTP/1.1" 404 Not Found "Wrong path"

failed to push ...
completed with errors ...
```

**Comment by artemkin** [comment]
Yeah, I've implemented Batch API, but not released yet. I will do that in a couple of days.

**Comment by leptitchris** [comment]
Hey Artemkin, thanks for all the work you've put into this project. I believe I'm also having this issue, do you know when you are thinking of releasing the new implemented Batch API feature?

**Comment by artemkin** [comment]
Sorry for the delay, guys. I've just released it. Batch API is supported starting from v0.3.0.

**Comment by rahul-ecsion** [comment]
Hi @artemkin I am facing issue for lockable files push:
```
2020-05-19 18:17:42.967160+05:30 Error 192.168.43.23 "POST /locks/verify HTTP/1.1" 404 Not Found "Wrong path"
```
could you please help me with this?
