### ISSUE TITLE
How do I build the software?

### ISSUE THREAD

**Issue by arkdae** [artemkin/git-lfs-server#6]
I am unable to build the software. I have upgraded Ocaml to 4.04.0, and I have installed sexplib via opam. I have guessed at the build command line as there is no documentation:

```
> scripts/build.sh src/lfs_server.native
+ ocamlfind ocamldep -syntax camlp4o -package sexplib.syntax -package core,async,async_ssl,cohttp,cohttp.async,yojson,cryptokit,simple_pam -modules src/lfs_server.ml > src/lfs_server.ml.depends
ocamlfind: Package `sexplib.syntax' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.

```

**Comment by artemkin** [comment]
You should be able to install the binary package. I will check compilation with OCaml 4.04 a bit later today.

**Comment by artemkin** [comment]
I've just pushed the fix. It generates a bunch of warnings, but it seems working and tests are passed. Checked with 4.03, but it should work with 4.04.
