### ISSUE TITLE
exception while running

### ISSUE THREAD

**Issue by jeras** [artemkin/git-lfs-server#8]
Tried to run version 0.3.0 on Ubuntu 17.10 with the command line for server without authentication:
```
$ sudo ./lfs_server.sh -verbose -s localhost -p 8080
Uncaught exception:
  
  (Unix.Unix_error "Illegal seek" sysconf "")

Raised by primitive operation at file "src/core_unix.ml", line 347, characters 14-29
```

**Comment by artemkin** [comment]
It seems Ocaml library didn't correctly handle sysconf result with glibc-2.26 https://github.com/janestreet/core/issues/95. Let me prepare a new release.

**Comment by artemkin** [comment]
@jeras check 0.3.1 https://github.com/artemkin/git-lfs-server/releases/download/v0.3.1/lfs_server-0.3.1-linux.x64.tar.gz

**Comment by jeras** [comment]
Thanks artemkin, I will test the new release later today.

**Comment by jeras** [comment]
Hi @artemkin, the issue is fixed now, the server started properly. Thanks.
But I found out I do not know how to integrate it with a git repo.

My intention was to use it to run some LFS tests, but I kind of lost interest, sorry.

Right now it seems Microsoft GVFS might be a better choice, since as I understand it keeps all files in a central server repo, instead of using a separate location. This makes it easier to move the server side repository without loosing data.
Unfortunately GVFS is only available on Windows, although server side MS and Bitbucket should have some support.

Another thing that would make sense for my usage cases is file locking, I quickly tried what is provided on GitHub, I suspect you did not implement it yet.

So for now I will probably stick to standard git and continue evaluating when some progress is made by server providers (GitLab, Bitbucket), and ...
